version: 0.1

phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - docker login --username="$DOCKER_HUB_USERNAME" --password="$DOCKER_HUB_PASSWORD"          
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME:v_`echo $CODEBUILD_BUILD_ID |awk -F':' '{print $2}'` .
      - docker tag $IMAGE_REPO_NAME:v_`echo $CODEBUILD_BUILD_ID |awk -F':' '{print $2}'` $IMAGE_REPO_NAME:v_`echo $CODEBUILD_BUILD_ID |awk -F':' '{print $2}'`
      - mkdir -p ./configs/`echo $CODEBUILD_BUILD_ID |awk -F':' '{print $1}'`/`echo $CODEBUILD_BUILD_ID |awk -F':' '{print $2}'`
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $IMAGE_REPO_NAME:v_`echo $CODEBUILD_BUILD_ID |awk -F':' '{print $2}'`
      - sed -e "s;%BUILD_NUMBER%;`echo $CODEBUILD_BUILD_ID |awk -F':' '{print $2}'`;g" task-def.json > ./configs/`echo $CODEBUILD_BUILD_ID |awk -F':' '{print $1}'`/`echo $CODEBUILD_BUILD_ID |awk -F':' '{print $2}'`/task-def.json
artifacts:
  files:
    - configs/**/*
